### ISSUE TITLE
Option "use_lookup_dn_username" from ldapauthenticator missing

### ISSUE THREAD

**Issue by petimmermann** [jupyterhub/helm-chart#110]
The ldapauthenticator parameter "use_lookup_dn_username" introduced in version 1.3 https://github.com/jupyterhub/ldapauthenticator/pull/105 is set to "true" by default while setting this to "false" is exactly what we need to have the user's sAMAccountName used as jhub username, pvc and pod naming and so on. Unfortunately there's apparently no way to set this option via the helm chart. 

We would love if the current version of the helm chart (0.9.0) would also be able to control all the options provided from the new ldapauthenticator version it is provisioning. Is it possible to take the mentioned option into consideration for the jupyterhub helm chart?

Thanks in advance and thanks for the great work on this amazing project in general,
Peter

**Comment by consideRatio** [comment]
Hi Peter!

I think you can use the following general configuration mechanisms. We may indeed lack support for configuring it in `auth` which have been unsustainable to maintain a mapping to other projects from.

See if this can help you!

Either...

```yaml
# in config.yaml for the helm chart
config:
  c.ClassNameHere.configurable_option_here: value-here
```

Or...

```yaml
# in config.yaml for the helm chart
hub:
  extraConfig:
    c.ClassNameHere.configurable_option_here: value-here
```
