### ISSUE TITLE
Providing extraEnv as list not possible due to values.schema.json

### ISSUE THREAD

**Issue by mseiwald** [jupyterhub/helm-chart#128]
### Bug description
When providing `extraEnv` as a list like below the value schema validation fails since the value's type is set to `object`.
```
        extraEnv:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
```

#### Expected behaviour
`extraEnv` should accept both map and array to support rich environment variables (e.g. reference secrets)

#### Actual behaviour
```  
  Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
  jupyterhub:
  - hub.extraEnv: Invalid type. Expected: object, given: array
```

**Comment by consideRatio** [comment]
> extraEnv should accept both map and array to support rich environment variables (e.g. reference secrets)

This is supported as a map without using array as well, see: https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extraenv

```yaml
    THIS_KEY_DOES_NOT_MATTER_WITH_name_SET_BELOW:
      name: MY_SECRET_VALUE
      valueFrom:
        secretKeyRef:
          name: my-k8s-secret
          key: password
```
