### ISSUE TITLE
Unsure how to hook into a gitlab authorization authentication service with helm

### ISSUE THREAD

**Issue by mjschmidt** [jupyterhub/helm-chart#97]
I am not really sure how I take this section of the yaml and set it to a gitlab application? Maybe its not yet supported in the helm chart yet?
```
auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password:
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:
```
